version: "3.8" # Updated version
services:
  mariadb:
    image: mariadb:10.8
    healthcheck:
      test: 'mysqladmin ping -h localhost --password=123'
      interval: 1s
      retries: 20
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frappe.loadbalancer.server.port=8201"
    ports:
      - 8201
      - 9201

volumes:
  mariadb-data:
